#!/usr/bin/env python
"""embed_font.py -- turns a font file into a committed C++ byte-array header.

Usage: python embed_font.py <font.ttf> <output.h> <array_name>

Why a generated header rather than a shipped file beside mgmp.dll: this
project compiles every third-party payload straight into the DLL (MinHook,
stb_image, Dear ImGui) rather than adding a second file a deployment step can
forget to copy -- see CLAUDE.md's mod-architecture note. A font is no
different. The .ttf itself still lives under third_party/fonts/<name>/,
committed as upstream shipped it (repo convention), and this script is how
the header gets re-derived from it if the font ever needs to be swapped.
"""
import sys


def main():
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <font.ttf> <output.h> <array_name>")
        return 1
    src_path, out_path, array_name = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(src_path, "rb") as f:
        data = f.read()

    guard = array_name.upper()
    with open(out_path, "w", newline="\n") as f:
        f.write(f"// GENERATED by tools/embed_font.py from {src_path.split('/')[-1]}.\n")
        f.write("// DO NOT EDIT BY HAND -- re-run the script to regenerate.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n#include <cstddef>\n\n")
        f.write("namespace mgmp {\n\n")
        f.write(f"constexpr unsigned char {array_name}[] = {{\n")
        for i in range(0, len(data), 20):
            chunk = data[i:i + 20]
            f.write("    " + ",".join(str(b) for b in chunk) + ",\n")
        f.write("};\n")
        f.write(f"constexpr size_t {array_name}_size = sizeof({array_name});\n\n")
        f.write("} // namespace mgmp\n")

    print(f"wrote {out_path}: {len(data)} bytes -> {array_name}[]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
